data:
  general:
    input_size: 299
    n_fft: 512
    n_mels: 40
    win_length: 250
    hop_length: 100
    n_class: 103 # get from dataset externally 
    batch_size: 4
    num_workers: 2
  train:
    json_file: ..\s2idata\train_flower_en2vi.json
    img_path: ..\s2idata\image_oxford\image_oxford\train
    audio_path: ..\s2idata\oxford_audio\oxford\train
    input_size: ${data.general.input_size}
    n_fft: ${data.general.n_fft}
    n_mels: ${data.general.n_mels}
    win_length: ${data.general.win_length}
    hop_length: ${data.general.hop_length}
  test:
    json_file: ..\s2idata\test_flower_en2vi.json
    img_path: ..\s2idata\image_oxford\image_oxford\test
    audio_path: ..\s2idata\oxford_audio\oxford\test
    input_size: ${data.general.input_size}
    n_fft: ${data.general.n_fft}
    n_mels: ${data.general.n_mels}
    win_length: ${data.general.win_length}
    hop_length: ${data.general.hop_length}

model:
  image_encoder:
    output_dim: 1024
  speech_encoder:
    input_dim: ${data.general.n_mels}
    cnn_dim: [64, 128]
    kernel_size: 6
    stride: 2
    rnn_dim: 512
    rnn_num_layers: 2
    rnn_type: gru
    rnn_dropout: 0.1
    rnn_bidirectional: True
    attn_heads: 1
    attn_dropout: 0.1
  classifier:
    in_features: ${model.image_encoder.output_dim}
    out_features: ${data.general.n_class}

optimizer:
  lr: 0.001

scheduler:
  use: true

experiment:
  train: true
  test: true
  max_epoch: 100
  log_wandb: true

loss:
  beta: 10